# Generated by Django 3.1.1 on 2020-10-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201003_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_json',
            new_name='itemsJson',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='msg_id',
            new_name='order_id',
        ),
    ]
