# Generated by Django 3.1.1 on 2020-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201003_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemsJson',
            new_name='items_Json',
        ),
    ]
